### ISSUE TITLE
生成的电子书文件内容会乱码。

### ISSUE THREAD

**Issue by Lenny-Hu** [moszeed/kindle-periodical#4]
kindle-periodical.js 第241行 修改为 ：
`var fileContent = '<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">'
                            + '<head>'
                                + '<meta content="http://www.w3.org/1999/xhtml; charset=utf-8" http-equiv="Content-Type" />'
                                + '<title></title>'
                            + '</head>'
                            + '<body>'
                            + _checkContent(article.content)
                            + '</body>'
                            + '</html>'`
这样中文就能正常显示了。

**Comment by moszeed** [comment]
and now on English, please!
